# Generated by Django 6.0.5 on 2026-07-01 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('opt_out', models.BooleanField(default=False)),
                ('opt_out_em', models.DateTimeField(blank=True, null=True)),
                ('token_opt_out', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_opt_out_expira_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['telefone'], name='contatos_co_telefon_4e1843_idx'), models.Index(fields=['email'], name='contatos_co_email_e7dda1_idx'), models.Index(fields=['opt_out'], name='contatos_co_opt_out_796709_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrupoContatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contatos', models.ManyToManyField(blank=True, related_name='grupos', to='contatos.contato')),
            ],
            options={
                'verbose_name': 'Grupo de Contatos',
                'verbose_name_plural': 'Grupos de Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
