# Generated by Django 6.0.5 on 2026-07-01 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ambos', 'Ambos')], max_length=20)),
                ('assunto_email', models.CharField(blank=True, max_length=255)),
                ('corpo', models.TextField(help_text='Use {{nome}}, {{telefone}}, {{email}} como variáveis dinâmicas.')),
                ('media', models.FileField(blank=True, null=True, upload_to='campanhas/midias/')),
                ('media_tipo', models.CharField(blank=True, choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contatos_extras', models.ManyToManyField(blank=True, related_name='campanhas_extras', to='contatos.contato')),
                ('grupos', models.ManyToManyField(blank=True, related_name='campanhas', to='contatos.grupocontatos')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='campanhas.templatemensagem')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='campanhas_c_status_c8f589_idx'), models.Index(fields=['agendada_para'], name='campanhas_c_agendad_8adedf_idx')],
            },
        ),
    ]
