# Generated by Copilot on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemensagem',
            name='midia_canais',
            field=models.CharField(
                choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ambos', 'Ambos')],
                default='whatsapp',
                help_text='Escolha em quais canais a mídia será usada.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='templatemensagem',
            name='incluir_link_opt_out',
            field=models.BooleanField(
                default=False,
                help_text='Adiciona o link de descadastro ao final da mensagem.',
            ),
        ),
        migrations.AddField(
            model_name='campanha',
            name='envios_inicio_em',
            field=models.DateTimeField(
                blank=True,
                help_text='Início da janela de envio. Se vazio, usa a data agendada ou o momento atual.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='campanha',
            name='envios_fim_em',
            field=models.DateTimeField(
                blank=True,
                help_text='Fim da janela de envio. O Celery distribui as tarefas dentro desse período.',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['envios_inicio_em'], name='campanhas_c_enviosi_0b9e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['envios_fim_em'], name='campanhas_c_enviosf_3f0d31_idx'),
        ),
    ]
