# Generated by Django 6.0.5 on 2026-07-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_campaign_media_channels_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campanha',
            new_name='campanhas_c_envios__c317bb_idx',
            old_name='campanhas_c_enviosi_0b9e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='campanha',
            new_name='campanhas_c_envios__30bb40_idx',
            old_name='campanhas_c_enviosf_3f0d31_idx',
        ),
    ]
