# Generated by Django 6.0.5 on 2026-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_rename_campanhas_c_enviosi_0b9e2a_idx_campanhas_c_envios__c317bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='delay_maximo_segundos',
            field=models.PositiveIntegerField(default=90, help_text='Intervalo máximo, em segundos, entre um envio e o próximo.'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='delay_minimo_segundos',
            field=models.PositiveIntegerField(default=20, help_text='Intervalo mínimo, em segundos, entre um envio e o próximo.'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='corpo',
            field=models.TextField(help_text='Use {{nome}} como variável dinâmica.'),
        ),
    ]
