# Generated by Django 6.0.5 on 2026-07-01 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('falha', 'Falha'), ('opt_out', 'Opt-out')], default='pendente', max_length=20)),
                ('mensagem_id_externo', models.CharField(blank=True, max_length=255)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('falha_motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='campanhas.campanha')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='contatos.contato')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='envios_envi_status_e17c97_idx'), models.Index(fields=['canal'], name='envios_envi_canal_05b7f3_idx'), models.Index(fields=['mensagem_id_externo'], name='envios_envi_mensage_b3d332_idx'), models.Index(fields=['campanha', 'status'], name='envios_envi_campanh_6dfb24_idx')],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'contato', 'canal'), name='unique_envio_por_campanha_contato_canal')],
            },
        ),
    ]
