# Generated by Copilot on 2026-07-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='envio',
            name='unique_envio_por_campanha_contato_canal',
        ),
    ]